#/pregen timeout in milliseconds (default: 50)
bpg-timeout: 50

#/legacypregen timeout in seconds (default: 15).
lpg-timeout: 15

#stop on disconnect (true/false)
stop-on-disconnect: true

#Don't allow players. (true/false)
no-players: true
#Exclude players with permission pregen.pregen.bypass
exclude_pregen.pregen.bypass: true

debug: false